### ISSUE TITLE
New Websocket is being created for every sendFrame call

### ISSUE THREAD

**Issue by praina** [Kartik-RTP/ProtoCreatAR#12]
Currently the app creates a new socket connection with server whenever its trying to send a frame which defeats the purpose of websocket itself . This needs to be corrected and a single connections needs to be utilized again and again.For this , we need to look at documentaion of AndroidAsync library probably

**Comment by Kartik-RTP** [comment]
looks like its resolved . Can be opened again if there is some problem with it .
